1) Создайте новую числовую переменную  new_var в данных mtcars, которая содержит единицы в строчках, если в машине не меньше четырёх карбюраторов (переменная "carb") или больше шести цилиндров (переменная "cyl"). В строчках, в которых условие не выполняется, должны стоять нули.

In [23]:
mtcars$new_var  <- ifelse(mtcars$carb >= 4 | mtcars$cyl > 6, 1, 0)
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb new_car
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4    1
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4    1
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2    1
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4    1
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2    1
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2    1
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4    1
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4    1
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3    1
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3    1
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3    1
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4    1
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4    1
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4    1
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2    1
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2    1
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2    1
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4    1
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2    1
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2    1
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2    1
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4    1
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6    1
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8    1
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2    1
                    new_var
Mazda RX4           1
Mazda RX4 Wag       1
Datsun 710          0
Hornet 4 Drive      0
Hornet Sportabout   1
Valiant             0
Duster 360          1
Merc 240D           0
Merc 230            0
Merc 280            1
Merc 280C           1
Merc 450SE          1
Merc 450SL          1
Merc 450SLC         1
Cadillac Fleetwood  1
Lincoln Continental 1
Chrysler Imperial   1
Fiat 128            0
Honda Civic         0
Toyota Corolla      0
Toyota Corona       0
Dodge Challenger    1
AMC Javelin         1
Camaro Z28          1
Pontiac Firebird    1
Fiat X1-9           0
Porsche 914-2       0
Lotus Europa        0
Ford Pantera L      1
Ferrari Dino        1
Maserati Bora       1
Volvo 142E          0

___
2) В уже существующей переменной my_vector сохранен вектор из 50 чисел.

Решите задачу используя конструкцию:


if () {

} else {

} 

Если среднее значение вектора my_vector больше 20, в переменную result сохраните "My mean is great",  если среднее значение my_vector меньше или равно 20 то в переменную result сохраните  строку "My mean is not so great".

In [5]:
my_vector = range(10:90)
result = ""
if (mean(my_vector) > 20) {
    result = "My mean is great"
} else {
    result = "My mean is not so great"
}
result

[1] "My mean is great"

___
3) В этой задаче от вас потребуется узнать некоторую информацию о типах данных в R самостоятельно! Встроенные в R данные AirPassengers - это новый для нас формат данных типа Time-Series. Изучите структуру этих данных, прежде чем начать решение задачи! Например напишите команды:

> ?AirPassengers # справка о данных  
> str(AirPassengers) # структура данных

В встроенных в R данных AirPassengers хранится 144 значения (количество пассажиров в месяц) с 1949 по 1960 год. Данные Time-Series очень похожи на вектор по своей структуре, например мы можем обратиться к любому из 144 элементов используя уже знакомую нам индексацию AirPassengers[1] или AirPassengers[56].

Можно вообще перевести исходные данные в вектор при помощи команды as.vector(AirPassengers) и продолжить с ними работу как с вектором.

И так ваша задача создать переменную good_months и сохранить в нее число пассажиров только в тех месяцах, в которых это число больше, чем показатель в предыдущем месяце.  

Важный момент! В R оператор : для создания последовательности имеет приоритет над арифметическими действиями. Таким образом, если у вас есть переменная i, равная 10, и вы хотите создать вектор от 1 до i - 1, воспользуйтесь скобками, чтобы указать последовательность действий.

In [41]:
good_months  <- AirPassengers[-1][(AirPassengers[-1] > AirPassengers[-length(AirPassengers)])]
good_months

 [1] 118 132 135 148 118 126 141 149 170 140 145 150 178 172 178 199 166 171 180
[20] 193 183 218 230 242 194 196 236 243 264 272 201 204 235 234 264 302 229 242
[39] 267 269 270 315 364 278 284 317 318 374 413 306 315 356 355 422 465 467 336
[58] 340 362 363 435 491 505 337 360 406 420 472 548 559 405 417 419 461 472 535
[77] 622 432

___
4)  Задачка для супер героев, повышенной сложности!

Для встроенных в R данных AirPassengers рассчитайте скользящее среднее с интервалом сглаживания равным 10. Напечатайте получившийся результат (первым значением в выводе должно быть среднее для элементов 1:10, во втором значении - среднее для элементов 2:11 и т.д., в последнем  - среднее для элементов 135 :144)

Все полученные значения средних сохраните в переменную moving_average.

Пример расчета для вектора из 11 элементов:

![1.png](1.png)

Соответственно, для наших данных из 144 наблюдений должно получиться 135 средних (первые и последние 4 средних):

129.8 129.0 129.0 127.3 ... 483.6 489.2 486.5 490.6

Важный момент! В R оператор : для создания последовательности имеет приоритет над арифметическими действиями. Таким образом, если у вас есть переменная i, равная 10, и вы хотите создать вектор от 1 до i - 1, воспользуйтесь скобками, чтобы указать последовательность действий.

> i <- 10  
> 1 : i - 1 # так мы создадим последовательность от 1 до 10, а потом вычтем единицу из каждого элемента  
> [1] 0 1 2 3 4 5 6 7 8 9

> 1 : (i - 1) # а вот так мы создадим последовательность от 1 до i - 1, то есть от 1 до 9.   
> [1] 1 2 3 4 5 6 7 8 9

Если вам потребуется создать вектор moving_average заранее, то есть несколько способов сделать это:
1. самый простой, но не очень правильный вариант - создать пустой вектор
moving_average <- c()

2. можно сразу создать вектор определенной длины и определенного типа:
moving_average <- numeric(135)
Такой вариант является более предпочтительным. Почему? Узнаем во второй части курса!)

А для тем, кто уже выбрал путь воина и не хочет использовать цикл - советую познакомиться с функцией cumsum. Подсказка: если у нас есть два вектора одинаковой длинны, то если из одного вектора вычесть второй вектор, мы найдем разность для первых элементов векторов, затем для вторых и т.д.

In [72]:
v = as.vector(AirPassengers)
n = 10
moving_average = (cumsum(v)[10:length(cumsum(v))] - c(0, cumsum(v)[1:(length(cumsum(v))-10)]))/10